# Generated by Django 5.2.8 on 2026-03-29 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('medium', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video Call'), ('in_person', 'In Person')], max_length=10)),
                ('has_conflict', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timeslots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('alternative', 'Alternative Proposed')], default='pending', max_length=15)),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('alternative', 'Alternative Proposed')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this activity proposal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_activities', to=settings.AUTH_USER_MODEL)),
                ('proposed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_activities', to=settings.AUTH_USER_MODEL)),
                ('alternative_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_for', to='schedule.timeslot')),
                ('timeslot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='schedule.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
